export const data = [
  {
    orderId: "#CM9801",
    user: "Natali Craig",
    project: "Landing Page",
    address: "Meadow Lane Oakland",
    date: "Just now",
    status: "In Progress",
  },
  {
    orderId: "#CM9802",
    user: "Kate Morrison",
    project: "CRM Admin pages",
    address: "Larry San Francisco",
    date: "A minute ago",
    status: "Complete",
  },
  {
    orderId: "#CM9803",
    user: "Drew Cano",
    project: "Client Project",
    address: "Bagwell Avenue Ocala",
    date: "1 hour ago",
    status: "Pending",
  },
  {
    orderId: "#CM9804",
    user: "Orlando Diggs",
    project: "Admin Dashboard",
    address: "Washburn Baton Rouge",
    date: "Yesterday",
    status: "Rejected",
  },
  {
    orderId: "#CM9805",
    user: "Andi Lane",
    project: "App Landing Page",
    address: "Nest Lane Olivette",
    date: "Feb 2, 2023",
    status: "Rejected",
  },
  {
    orderId: "#CM9805",
    user: "Andi Lane",
    project: "App Landing Page",
    address: "Nest Lane Olivette",
    date: "Feb 2, 2023",
    status: "Rejected",
  },
  {
    orderId: "#CM9804",
    user: "Orlando Diggs",
    project: "Admin Dashboard",
    address: "Washburn Baton Rouge",
    date: "Yesterday",
    status: "Rejected",
  },
  {
    orderId: "#CM9803",
    user: "Drew Cano",
    project: "Client Project",
    address: "Bagwell Avenue Ocala",
    date: "1 hour ago",
    status: "Pending",
  },
  {
    orderId: "#CM9802",
    user: "Kate Morrison",
    project: "CRM Admin pages",
    address: "Larry San Francisco",
    date: "A minute ago",
    status: "Complete",
  },
  {
    orderId: "#CM9801",
    user: "Natali Craig",
    project: "Landing Page",
    address: "Meadow Lane Oakland",
    date: "Just now",
    status: "In Progress",
  },

  {
    orderId: "#CM1011",
    user: "Alice Smith",
    project: "Portfolio Website",
    address: "Pine Street Seattle",
    date: "2 minutes ago",
    status: "In Progress",
  },
  {
    orderId: "#CM1012",
    user: "David Johnson",
    project: "E-Commerce Store",
    address: "Maple Avenue Austin",
    date: "Yesterday",
    status: "Complete",
  },
  {
    orderId: "#CM1013",
    user: "Lily Adams",
    project: "Social Media App",
    address: "Cedar Lane Miami",
    date: "Just now",
    status: "Pending",
  },
  {
    orderId: "#CM1014",
    user: "Ethan Walker",
    project: "Blog Platform",
    address: "Oak Boulevard Denver",
    date: "1 hour ago",
    status: "Rejected",
  },
  {
    orderId: "#CM1015",
    user: "Sophia Turner",
    project: "Marketing Dashboard",
    address: "Sunset Drive Dallas",
    date: "Jan 15, 2024",
    status: "Complete",
  },
  {
    orderId: "#CM1016",
    user: "Jack Carter",
    project: "E-Learning Platform",
    address: "Elm Street Chicago",
    date: "3 hours ago",
    status: "In Progress",
  },
  {
    orderId: "#CM1017",
    user: "Emily Barnes",
    project: "Event Management Tool",
    address: "Birch Road Boston",
    date: "5 minutes ago",
    status: "Pending",
  },
  {
    orderId: "#CM1018",
    user: "Michael Lewis",
    project: "Payment Gateway Integration",
    address: "Willow Lane Los Angeles",
    date: "2 days ago",
    status: "Rejected",
  },
  {
    orderId: "#CM1019",
    user: "Olivia Garcia",
    project: "Real Estate App",
    address: "Aspen Street San Diego",
    date: "1 week ago",
    status: "Complete",
  },
  {
    orderId: "#CM1020",
    user: "Lucas Bennett",
    project: "Inventory Management System",
    address: "Spruce Avenue New York",
    date: "4 hours ago",
    status: "In Progress",
  },

  {
    orderId: "#CM1021",
    user: "Harper Wilson",
    project: "Gym Management App",
    address: "Palm Street Orlando",
    date: "10 minutes ago",
    status: "In Progress",
  },
  {
    orderId: "#CM1022",
    user: "James Moore",
    project: "Restaurant Booking System",
    address: "Hillcrest Avenue Phoenix",
    date: "Yesterday",
    status: "Pending",
  },
  {
    orderId: "#CM1023",
    user: "Ella Davis",
    project: "Finance Dashboard",
    address: "Ocean Drive Miami",
    date: "2 hours ago",
    status: "Complete",
  },
  {
    orderId: "#CM1024",
    user: "Henry Martinez",
    project: "Crypto Trading Platform",
    address: "Rose Avenue Los Angeles",
    date: "Just now",
    status: "Rejected",
  },
  {
    orderId: "#CM1025",
    user: "Amelia Brown",
    project: "Online Course Portal",
    address: "Maple Drive New York",
    date: "Jan 5, 2024",
    status: "Complete",
  },
  {
    orderId: "#CM1026",
    user: "Logan Anderson",
    project: "Travel Booking App",
    address: "Elm Street San Francisco",
    date: "5 minutes ago",
    status: "In Progress",
  },
  {
    orderId: "#CM1027",
    user: "Ava Thomas",
    project: "Music Streaming Service",
    address: "Pine Lane Seattle",
    date: "2 days ago",
    status: "Pending",
  },
  {
    orderId: "#CM1028",
    user: "Mason Taylor",
    project: "Online Storefront",
    address: "Spruce Street Chicago",
    date: "1 week ago",
    status: "Complete",
  },
  {
    orderId: "#CM1029",
    user: "Mia Clark",
    project: "Video Conferencing Tool",
    address: "River Road Portland",
    date: "4 hours ago",
    status: "Rejected",
  },
  {
    orderId: "#CM1030",
    user: "Noah Hernandez",
    project: "Fitness Tracker",
    address: "Sunset Boulevard Los Angeles",
    date: "Yesterday",
    status: "In Progress",
  },
  {
    orderId: "#CM1031",
    user: "Isabella Robinson",
    project: "Event Registration App",
    address: "Broadway New York",
    date: "Just now",
    status: "Pending",
  },
  {
    orderId: "#CM1032",
    user: "Jacob Walker",
    project: "Job Board Platform",
    address: "Main Street Houston",
    date: "2 hours ago",
    status: "Complete",
  },
  {
    orderId: "#CM1033",
    user: "Emma White",
    project: "Task Management System",
    address: "Willow Avenue San Diego",
    date: "Jan 8, 2024",
    status: "Rejected",
  },
  {
    orderId: "#CM1034",
    user: "Liam Harris",
    project: "Chatbot Integration",
    address: "Cedar Drive San Antonio",
    date: "1 hour ago",
    status: "In Progress",
  },
  {
    orderId: "#CM1035",
    user: "Sophia Lee",
    project: "Smart Home Dashboard",
    address: "Birch Lane Denver",
    date: "3 days ago",
    status: "Complete",
  },
  {
    orderId: "#CM1036",
    user: "Benjamin Young",
    project: "Property Management App",
    address: "Park Avenue Atlanta",
    date: "4 hours ago",
    status: "Pending",
  },
  {
    orderId: "#CM1037",
    user: "Charlotte Allen",
    project: "News Aggregator",
    address: "Hillcrest Street Dallas",
    date: "Yesterday",
    status: "Rejected",
  },
  {
    orderId: "#CM1038",
    user: "William King",
    project: "Weather Forecast App",
    address: "Oak Street Las Vegas",
    date: "2 hours ago",
    status: "In Progress",
  },
  {
    orderId: "#CM1039",
    user: "Evelyn Wright",
    project: "Online Learning Platform",
    address: "Pine Grove San Diego",
    date: "Just now",
    status: "Pending",
  },
  {
    orderId: "#CM1040",
    user: "Lucas Scott",
    project: "Freelance Portfolio",
    address: "Ocean Boulevard Miami",
    date: "5 minutes ago",
    status: "Complete",
  },
  {
    orderId: "#CM1041",
    user: "Scarlett Hill",
    project: "Non-Profit Website",
    address: "Sunset Drive Austin",
    date: "Jan 12, 2024",
    status: "Rejected",
  },
  {
    orderId: "#CM1042",
    user: "Samuel Green",
    project: "Productivity App",
    address: "Lake Road Orlando",
    date: "2 days ago",
    status: "In Progress",
  },
  {
    orderId: "#CM1043",
    user: "Victoria Baker",
    project: "Meditation App",
    address: "Elm Street Denver",
    date: "Just now",
    status: "Complete",
  },
  {
    orderId: "#CM1044",
    user: "James Perez",
    project: "Online Survey Tool",
    address: "Main Avenue Chicago",
    date: "4 hours ago",
    status: "Pending",
  },
  {
    orderId: "#CM1045",
    user: "Isla Cooper",
    project: "Real Estate Website",
    address: "Maple Drive San Francisco",
    date: "Yesterday",
    status: "Rejected",
  },
  {
    orderId: "#CM1046",
    user: "Oliver Cox",
    project: "Delivery Tracking System",
    address: "Broadway New York",
    date: "2 days ago",
    status: "Complete",
  },
  {
    orderId: "#CM1047",
    user: "Amelia Diaz",
    project: "Medical Records Portal",
    address: "Pine Avenue Houston",
    date: "5 minutes ago",
    status: "In Progress",
  },
  {
    orderId: "#CM1048",
    user: "Ethan Murphy",
    project: "Music Streaming App",
    address: "Sunset Street Las Vegas",
    date: "3 hours ago",
    status: "Pending",
  },
  {
    orderId: "#CM1049",
    user: "Zoe Rivera",
    project: "Video Sharing Platform",
    address: "Hillcrest Lane Miami",
    date: "Just now",
    status: "Complete",
  },
];

export const revenueData = [
  { title: "Current Week", value: "$58,211" },
  { title: "Previous Week", value: "$68,768" },
];

export const tableData = [
  {
    name: "ASOS Ridley High Waist",
    price: "$79.49",
    quantity: 82,
    amount: "$6518.18",
  },
  {
    name: "Marco Lightweight Shirt",
    price: "$128.50",
    quantity: 37,
    amount: "$4754.50",
  },
  {
    name: "Half Sleeve Shirt",
    price: "$39.99",
    quantity: 64,
    amount: "$2559.36",
  },
  {
    name: "Lightweight Jacket",
    price: "$20.00",
    quantity: 184,
    amount: "$3680.00",
  },
  {
    name: "Long Sleeve Shirt",
    price: "$25.50",
    quantity: 10,
    amount: "$255.00",
  },
  {
    name: "Cotton T-Shirt",
    price: "$10.99",
    quantity: 184,
    amount: "$2023.16",
  },
  {
    name: "Lightweight Jacket",
    price: "$20.00",
    quantity: 184,
    amount: "$3680.00",
  },
  {
    name: "Long Sleeve Shirt",
    price: "$25.50",
    quantity: 10,
    amount: "$255.00",
  },
  {
    name: "Cotton T-Shirt",
    price: "$10.99",
    quantity: 184,
    amount: "$2023.16",
  },
  {
    name: "Lightweight Jacket",
    price: "$20.00",
    quantity: 184,
    amount: "$3680.00",
  },
  {
    name: "Long Sleeve Shirt",
    price: "$25.50",
    quantity: 10,
    amount: "$255.00",
  },
  {
    name: "Cotton T-Shirt",
    price: "$10.99",
    quantity: 184,
    amount: "$2023.16",
  },
  {
    name: "Lightweight Jacket",
    price: "$20.00",
    quantity: 184,
    amount: "$3680.00",
  },
  {
    name: "Long Sleeve Shirt",
    price: "$25.50",
    quantity: 10,
    amount: "$255.00",
  },
  {
    name: "Cotton T-Shirt",
    price: "$10.99",
    quantity: 184,
    amount: "$2023.16",
  },
  {
    name: "Lightweight Jacket",
    price: "$20.00",
    quantity: 184,
    amount: "$3680.00",
  },
];

export const PieChartdata = [
  { name: "Direct", value: 300.56 },
  { name: "Affilliate", value: 135.18 },
  { name: "Sponsored", value: 154.02 },
  { name: "E-mail", value: 48.96 },
];

export const revenueDataCountry = [
  { location: "New York", revenue: 72, maxRevenue: 100 },
  { location: "San Francisco", revenue: 39, maxRevenue: 100 },
  { location: "Sydney", revenue: 25, maxRevenue: 100 },
  { location: "Singapore", revenue: 61, maxRevenue: 100 },
];
export const boxes = [
  {
    name: "Customers",
    number: "3,781",
    hike: "+11.01%",
    link: "/",
  },
  {
    name: "Orders",
    number: "1,219",
    hike: "-0.03%",
    link: "/orders",
  },
  {
    name: "Revenue",
    number: "$695",
    hike: "+15.03%",
    link: "/",
  },
  {
    name: "Growth",
    number: "30.1%",
    hike: "+6.08%",
    link: "/",
  },
];

export const tableHeaders = [
  { name: "Name", key: "name" },
  { name: "Price", key: "price" },
  { name: "Quantity", key: "quantity" },
  { name: "Amount", key: "amount" },
];
